apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-htaccess-config
  namespace: bazalt
  labels:
    app:  wp-space
data: 
  .htaccess: |
    # BEGIN WordPress

    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]

    # END WordPress