<?php

add_action( 'init', 'register_post_types' );
function register_post_types(){
    //mail
    register_post_type( 'mail', [
		'label'  => null,
		'labels' => [
			'name'               => 'Заявки',
			'singular_name'      => 'Заявка',
			'add_new'            => 'Добавить заявки',
			'add_new_item'       => 'Добавление заявки',
			'edit_item'          => 'Редактирование заявки',
			'new_item'           => 'Новая заявка',
			'view_item'          => 'Смотреть заявку',
			'search_items'       => 'Искать заявку',
			'not_found'          => 'Не найдено',
			'not_found_in_trash' => 'Не найдено в корзине',
			'parent_item_colon'  => '',
			'menu_name'          => 'Заявки',
		],
		'description'         => 'Заявки с сайта',
		'public'              => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'rest_base'           => null,
		'menu_position'       => 22,
		'menu_icon'           => 'dashicons-email',
		'hierarchical'        => false,
		'supports'            => [ 'title', 'editor' ],
		'taxonomies'          => [],
		'has_archive'         => false,
		'rewrite'             => true,
		'query_var'           => true,
        'publicly_queryable'  => false,
	] );

    //blog
    register_taxonomy( 'blog_category', [ 'blog' ], [
        'label'                 => '',
        'labels'                => [
            'name'                     => 'Категории',
            'singular_name'            => 'Категория',
            'menu_name'                => 'Категории',
            'all_items'                => 'Все категории',
            'edit_item'                => 'Изменить категорию',
            'view_item'                => 'Просмотр категории',
            'update_item'              => 'Обновить категорию',
            'add_new_item'             => 'Добавить новую категорию',
            'new_item_name'            => 'Название новой категории',
            'parent_item'              => 'Родительская категория',
            'parent_item_colon'        => 'Родительская категория:',
            'search_items'             => 'Искать категорию',
            'popular_items'            => 'Популярные категории',
            'separate_items_with_commas' => 'Разделяйте категории запятыми',
            'add_or_remove_items'      => 'Добавить или удалить категорию',
            'choose_from_most_used'    => 'Выбрать из часто используемых категорий',
            'not_found'                => 'Категория не найдена',
            'back_to_items'            => '← Назад к категориям',
        ],
        'description'           => '',
        'public'                => true,
        'publicly_queryable'    => true,
        'hierarchical'          => true,
        'rewrite'               => array( 'slug' => 'blog/category' ),
        'capabilities'          => array(),
        'meta_box_cb'           => null,
        'show_admin_column'     => true,
        'show_in_rest'          => true,
        'rest_base'             => null,
        'template_item'         => '/templates/blog/blog-archive.php',
    ] );

    register_post_type( 'blog', [
		'label'  => null,
		'labels' => [
			'name'               => 'Статьи',
			'singular_name'      => 'Статья',
			'add_new'            => 'Добавить статью',
			'add_new_item'       => 'Добавление статьи',
			'edit_item'          => 'Редактирование статьи',
			'new_item'           => 'Новая статья',
			'view_item'          => 'Смотреть статью',
			'search_items'       => 'Искать статью',
			'not_found'          => 'Не найдено',
			'not_found_in_trash' => 'Не найдено в корзине',
			'parent_item_colon'  => '',
			'menu_name'          => 'Блог',
		],
		'description'         => 'Блог',
		'public'              => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'rest_base'           => null,
		'menu_position'       => 22,
		'menu_icon'           => 'dashicons-format-aside',
		'hierarchical'        => false,
		'supports'            => [ 'title', 'thumbnail', 'editor' ],
		'taxonomies'          => [ 'blog_category' ],
		'has_archive'         => true,
		'rewrite'             => true,
		'query_var'           => true,
        'template_item'       => '/templates/blog/blog-single.php',
        'template_archive'    => '/templates/blog/blog-archive.php',
	] );
    
    //vacancies
    register_taxonomy( 'vacancies_city', [ 'vacancies' ], [
        'label'                 => '',
        'labels'                => [
            'name'                     => 'Города',
            'singular_name'            => 'Город',
            'menu_name'                => 'Города',
            'all_items'                => 'Все города',
            'edit_item'                => 'Изменить город',
            'view_item'                => 'Просмотр города',
            'update_item'              => 'Обновить город',
            'add_new_item'             => 'Добавить новый город',
            'new_item_name'            => 'Название нового города',
            'parent_item'              => 'Родительский город',
            'parent_item_colon'        => 'Родительский город:',
            'search_items'             => 'Искать город',
            'popular_items'            => 'Популярные города',
            'separate_items_with_commas' => 'Разделяйте города запятыми',
            'add_or_remove_items'      => 'Добавить или удалить город',
            'choose_from_most_used'    => 'Выбрать из часто используемых городов',
            'not_found'                => 'Город не найден',
            'back_to_items'            => '← Назад к городам',
        ],
        'description'           => '',
        'public'                => true,
        'publicly_queryable'    => true,
        'hierarchical'          => true,
        'rewrite'               => array( 'slug' => 'vacancies/city' ),
        'capabilities'          => array(),
        'meta_box_cb'           => null,
        'show_admin_column'     => true,
        'show_in_rest'          => true,
        'rest_base'             => null,
        'template_item'         => '/templates/vacancies/vacancies-archive.php',
    ] );

    register_post_type( 'vacancies', [
		'label'  => null,
		'labels' => [
			'name'               => 'Вакансии',
			'singular_name'      => 'Вакансия',
			'add_new'            => 'Добавить вакансию',
			'add_new_item'       => 'Добавление вакансии',
			'edit_item'          => 'Редактирование вакансии',
			'new_item'           => 'Новая вакансия',
			'view_item'          => 'Смотреть вакансию',
			'search_items'       => 'Искать вакансию',
			'not_found'          => 'Не найдено',
			'not_found_in_trash' => 'Не найдено в корзине',
			'parent_item_colon'  => '',
			'menu_name'          => 'Вакансии',
		],
		'description'         => 'Вакансии',
		'public'              => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'rest_base'           => null,
		'menu_position'       => 22,
		'menu_icon'           => 'dashicons-buddicons-buddypress-logo',
		'hierarchical'        => false,
		'supports'            => [ 'title', 'editor' ],
		'taxonomies'          => [ 'vacancies_city' ],
		'has_archive'         => true,
		'rewrite'             => true,
		'query_var'           => true,
        'template_item'       => '/templates/vacancies/vacancies-single.php',
        'template_archive'    => '/templates/vacancies/vacancies-archive.php',
	] );

    register_post_type( 'matrix', [
		'label'  => null,
		'labels' => [
			'name'               => 'Матрица',
			'singular_name'      => 'Матрица',
			'add_new'            => 'Добавить матрицу',
			'add_new_item'       => 'Добавление матрицы',
			'edit_item'          => 'Редактирование матрицы',
			'new_item'           => 'Новая матрица',
			'view_item'          => 'Смотреть матрицу',
			'search_items'       => 'Искать матрицу',
			'not_found'          => 'Не найдено',
			'not_found_in_trash' => 'Не найдено в корзине',
			'parent_item_colon'  => '',
			'menu_name'          => 'Матрица',
		],
		'description'         => 'Матрица',
		'public'              => true,
        'publicly_queryable'  => false,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'rest_base'           => null,
		'menu_position'       => 22,
		'menu_icon'           => 'dashicons-image-filter',
		'hierarchical'        => false,
		'supports'            => [ 'title' ],
		'taxonomies'          => [],
		'has_archive'         => false,
		'rewrite'             => true,
		'query_var'           => true,
	] );
}
