<?php

add_action( 'init', 'register_post_types' );
function register_post_types(){
    //mail
    register_post_type( 'mail', [
		'label'  => null,
		'labels' => [
			'name'               => 'Заявки',
			'singular_name'      => 'Заявка',
			'add_new'            => 'Добавить заявки',
			'add_new_item'       => 'Добавление заявки',
			'edit_item'          => 'Редактирование заявки',
			'new_item'           => 'Новая заявка',
			'view_item'          => 'Смотреть заявку',
			'search_items'       => 'Искать заявку',
			'not_found'          => 'Не найдено',
			'not_found_in_trash' => 'Не найдено в корзине',
			'parent_item_colon'  => '',
			'menu_name'          => 'Заявки',
		],
		'description'         => 'Заявки с сайта',
		'public'              => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'rest_base'           => null,
		'menu_position'       => 22,
		'menu_icon'           => 'dashicons-email',
		'hierarchical'        => false,
		'supports'            => [ 'title', 'editor' ],
		'taxonomies'          => [],
		'has_archive'         => false,
		'rewrite'             => true,
		'query_var'           => true,
        'publicly_queryable'  => false,
	] );

    //blog
    register_taxonomy( 'blog_category', [ 'blog' ], [
        'label'                 => '',
        'labels'                => [
            'name'                     => 'Категории',
            'singular_name'            => 'Категория',
            'menu_name'                => 'Категории',
            'all_items'                => 'Все категории',
            'edit_item'                => 'Изменить категорию',
            'view_item'                => 'Просмотр категории',
            'update_item'              => 'Обновить категорию',
            'add_new_item'             => 'Добавить новую категорию',
            'new_item_name'            => 'Название новой категории',
            'parent_item'              => 'Родительская категория',
            'parent_item_colon'        => 'Родительская категория:',
            'search_items'             => 'Искать категорию',
            'popular_items'            => 'Популярные категории',
            'separate_items_with_commas' => 'Разделяйте категории запятыми',
            'add_or_remove_items'      => 'Добавить или удалить категорию',
            'choose_from_most_used'    => 'Выбрать из часто используемых категорий',
            'not_found'                => 'Категория не найдена',
            'back_to_items'            => '← Назад к категориям',
        ],
        'description'           => '',
        'public'                => true,
        'publicly_queryable'    => true,
        'hierarchical'          => true,
        'rewrite'               => array( 'slug' => 'blog' ),
        'capabilities'          => array(),
        'meta_box_cb'           => null,
        'show_admin_column'     => true,
        'show_in_rest'          => true,
        'rest_base'             => null,
        'template_item'         => '/templates/blog/blog-archive.php',
    ] );

    register_post_type( 'blog', [
		'label'  => null,
		'labels' => [
			'name'               => 'Статьи',
			'singular_name'      => 'Статья',
			'add_new'            => 'Добавить статью',
			'add_new_item'       => 'Добавление статьи',
			'edit_item'          => 'Редактирование статьи',
			'new_item'           => 'Новая статья',
			'view_item'          => 'Смотреть статью',
			'search_items'       => 'Искать статью',
			'not_found'          => 'Не найдено',
			'not_found_in_trash' => 'Не найдено в корзине',
			'parent_item_colon'  => '',
			'menu_name'          => 'Блог',
		],
		'description'         => 'Блог',
		'public'              => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'rest_base'           => null,
		'menu_position'       => 22,
		'menu_icon'           => 'dashicons-format-aside',
		'hierarchical'        => false,
		'supports'            => [ 'title', 'thumbnail', 'editor' ],
		'taxonomies'          => [ 'blog_category' ],
		'has_archive'         => true,
		'rewrite'             => array( 'slug' => 'article' ),
		'query_var'           => true,
        'template_item'       => '/templates/blog/blog-single.php',
        'template_archive'    => '/templates/blog/blog-archive.php',
	] );
    
    //vacancies
    register_taxonomy( 'vacancies_city', [ 'vacancies' ], [
        'label'                 => '',
        'labels'                => [
            'name'                     => 'Города',
            'singular_name'            => 'Город',
            'menu_name'                => 'Города',
            'all_items'                => 'Все города',
            'edit_item'                => 'Изменить город',
            'view_item'                => 'Просмотр города',
            'update_item'              => 'Обновить город',
            'add_new_item'             => 'Добавить новый город',
            'new_item_name'            => 'Название нового города',
            'parent_item'              => 'Родительский город',
            'parent_item_colon'        => 'Родительский город:',
            'search_items'             => 'Искать город',
            'popular_items'            => 'Популярные города',
            'separate_items_with_commas' => 'Разделяйте города запятыми',
            'add_or_remove_items'      => 'Добавить или удалить город',
            'choose_from_most_used'    => 'Выбрать из часто используемых городов',
            'not_found'                => 'Город не найден',
            'back_to_items'            => '← Назад к городам',
        ],
        'description'           => '',
        'public'                => true,
        'publicly_queryable'    => true,
        'hierarchical'          => true,
        'rewrite'               => array( 'slug' => 'vacancies/city' ),
        'capabilities'          => array(),
        'meta_box_cb'           => null,
        'show_admin_column'     => true,
        'show_in_rest'          => true,
        'rest_base'             => null,
        'template_item'         => '/templates/vacancies/vacancies-archive.php',
    ] );

    register_post_type( 'vacancies', [
		'label'  => null,
		'labels' => [
			'name'               => 'Вакансии',
			'singular_name'      => 'Вакансия',
			'add_new'            => 'Добавить вакансию',
			'add_new_item'       => 'Добавление вакансии',
			'edit_item'          => 'Редактирование вакансии',
			'new_item'           => 'Новая вакансия',
			'view_item'          => 'Смотреть вакансию',
			'search_items'       => 'Искать вакансию',
			'not_found'          => 'Не найдено',
			'not_found_in_trash' => 'Не найдено в корзине',
			'parent_item_colon'  => '',
			'menu_name'          => 'Вакансии',
		],
		'description'         => 'Вакансии',
		'public'              => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'rest_base'           => null,
		'menu_position'       => 22,
		'menu_icon'           => 'dashicons-buddicons-buddypress-logo',
		'hierarchical'        => false,
		'supports'            => [ 'title', 'editor' ],
		'taxonomies'          => [ 'vacancies_city' ],
		'has_archive'         => true,
		'rewrite'             => true,
		'query_var'           => true,
        'template_item'       => '/templates/vacancies/vacancies-single.php',
        'template_archive'    => '/templates/vacancies/vacancies-archive.php',
	] );

    register_post_type( 'matrix', [
		'label'  => null,
		'labels' => [
			'name'               => 'Матрица',
			'singular_name'      => 'Матрица',
			'add_new'            => 'Добавить матрицу',
			'add_new_item'       => 'Добавление матрицы',
			'edit_item'          => 'Редактирование матрицы',
			'new_item'           => 'Новая матрица',
			'view_item'          => 'Смотреть матрицу',
			'search_items'       => 'Искать матрицу',
			'not_found'          => 'Не найдено',
			'not_found_in_trash' => 'Не найдено в корзине',
			'parent_item_colon'  => '',
			'menu_name'          => 'Матрица',
		],
		'description'         => 'Матрица',
		'public'              => true,
        'publicly_queryable'  => false,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'rest_base'           => null,
		'menu_position'       => 22,
		'menu_icon'           => 'dashicons-image-filter',
		'hierarchical'        => false,
		'supports'            => [ 'title' ],
		'taxonomies'          => [],
		'has_archive'         => false,
		'rewrite'             => true,
		'query_var'           => true,
	] );

    register_post_type( 'partner', [
        'label'  => null,
        'labels' => [
            'name'               => 'Партнеры',
            'singular_name'      => 'Партнеры',
            'add_new'            => 'Добавить партнера',
            'add_new_item'       => 'Добавление партнера',
            'edit_item'          => 'Редактирование партнера',
            'new_item'           => 'Новая партнер',
            'view_item'          => 'Смотреть партнер',
            'search_items'       => 'Искать партнера',
            'not_found'          => 'Не найдено',
            'not_found_in_trash' => 'Не найдено в корзине',
            'parent_item_colon'  => '',
            'menu_name'          => 'Партнеры',
        ],
        'description'         => 'Партнеры',
        'public'              => true,
        'publicly_queryable'  => false,
        'show_in_menu'        => true,
        'show_in_rest'        => true,
        'rest_base'           => null,
        'menu_position'       => 22,
        'menu_icon'           => 'dashicons-businessman',
        'hierarchical'        => false,
        'supports'            => [ 'title' ],
        'taxonomies'          => [],
        'has_archive'         => false,
        'rewrite'             => true,
        'query_var'           => true,
    ] );

    register_post_type( 'cases', [
        'label'  => null,
        'labels' => [
            'name'               => 'Кейсы',
            'singular_name'      => 'Кейс',
            'add_new'            => 'Добавить кейс',
            'add_new_item'       => 'Добавление кейса',
            'edit_item'          => 'Редактирование кейса',
            'new_item'           => 'Новый кейс',
            'view_item'          => 'Смотреть кейс',
            'search_items'       => 'Искать кейс',
            'not_found'          => 'Не найдено',
            'not_found_in_trash' => 'Не найдено в корзине',
            'parent_item_colon'  => '',
            'menu_name'          => 'Кейсы',
        ],
        'description'         => 'Кейсы',
        'public'              => true,
        'publicly_queryable'  => true,
        'show_in_menu'        => true,
        'show_in_rest'        => true,
        'rest_base'           => null,
        'menu_position'       => 22,
        'menu_icon'           => 'dashicons-grid-view',
        'hierarchical'        => false,
        'supports'            => [ 'title', 'thumbnail', 'editor' ],
        'taxonomies'          => [],
        'has_archive'         => false,
        'rewrite'             => true,
        'query_var'           => true,
        'template_item'       => '/templates/cases/cases-single.php',
        'template_archive'    => '/templates/cases/cases.php',
    ] );

    register_taxonomy('case_tags', ['cases'], [
        'label'        => 'Теги кейсов',
        'labels'       => [
            'name'          => 'Теги кейсов',
            'singular_name' => 'Тег кейса',
            'menu_name'     => 'Теги',
        ],
        'public'       => true,
        "exclude_from_search" => true,
        'hierarchical' => false,
        'show_in_rest' => true,
    ]);

    register_taxonomy( 'glossary_category', [ 'glossary_term' ], [
        'labels' => [
            'name'                       => 'Категории глоссария',
            'singular_name'              => 'Категория глоссария',
            'menu_name'                  => 'Категории',
            'all_items'                  => 'Все категории',
            'edit_item'                  => 'Изменить категорию',
            'view_item'                  => 'Просмотр категории',
            'update_item'                => 'Обновить категорию',
            'add_new_item'               => 'Добавить категорию',
            'new_item_name'              => 'Название новой категории',
            'parent_item'                => 'Родительская категория',
            'parent_item_colon'          => 'Родительская категория:',
            'search_items'               => 'Искать категории',
            'not_found'                  => 'Категории не найдены',
            'back_to_items'              => '← Назад к категориям',
        ],
        'description'           => 'Категории терминов глоссария',
        'public'                => false,
        'publicly_queryable'    => false,
        'show_ui'               => true,
        'show_admin_column'     => true,
        'show_in_nav_menus'     => false,
        'show_tagcloud'         => false,
        'show_in_quick_edit'    => true,
        'show_in_rest'          => true,
        'hierarchical'          => true,
        'rewrite'               => false,
        'query_var'             => false,
    ] );

    register_post_type( 'glossary_term', [
        'labels' => [
            'name'                  => 'Термины глоссария',
            'singular_name'         => 'Термин глоссария',
            'menu_name'             => 'Термины глоссария',
            'name_admin_bar'        => 'Термин глоссария',
            'add_new'               => 'Добавить термин',
            'add_new_item'          => 'Добавление термина',
            'edit_item'             => 'Редактирование термина',
            'new_item'              => 'Новый термин',
            'view_item'             => 'Смотреть термин',
            'view_items'            => 'Смотреть термины',
            'search_items'          => 'Искать термины',
            'not_found'             => 'Термины не найдены',
            'not_found_in_trash'    => 'В корзине термины не найдены',
            'all_items'             => 'Все термины',
            'archives'              => 'Глоссарий',
            'attributes'            => 'Атрибуты термина',
            'insert_into_item'      => 'Вставить в термин',
            'uploaded_to_this_item' => 'Загружено для этого термина',
            'title_placeholder'     => 'Название термина',
        ],
        'description'          => 'Термины глоссария',
        'public'               => true,
        'publicly_queryable'   => true,
        'exclude_from_search'  => false,
        'show_ui'              => true,
        'show_in_menu'         => true,
        'show_in_rest'         => true,
        'menu_position'        => 22,
        'menu_icon'            => 'dashicons-book-alt',
        'capability_type'      => 'post',
        'map_meta_cap'         => true,
        'hierarchical'         => false,
        'supports'             => [ 'title', 'editor', 'revisions' ],
        'template'             => [
            [
                'acf/glossary-term-data',
                [
                    'lock' => [
                        'move'   => true,
                        'remove' => true,
                    ],
                ],
            ],
        ],
        'taxonomies'           => [ 'glossary_category' ],
        'has_archive'          => 'glossary',
        'rewrite'              => [
            'slug'       => 'glossary',
            'with_front' => false,
            'feeds'      => false,
            'pages'      => false,
        ],
        'query_var'            => true,
        'template_item'        => '/templates/glossary/glossary-single.php',
        'template_archive'     => '/templates/glossary/glossary-archive.php',
    ] );
}
